import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { loadApplicationConfiguration } from "./application-config";

const projectRoot = resolve(import.meta.dir, "..");
const applicationConfiguration = await loadApplicationConfiguration();
const outputPath = resolve(
  projectRoot,
  "app/src/lib/generated/application-config.ts",
);

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  [
    "// This file is generated by scripts/generate-app-config.ts. Do not edit it.",
    "export type AppConfig = { brand: { tenantId: string; productName: string } };",
    `export const appConfig: AppConfig = ${JSON.stringify(applicationConfiguration, null, 2)};`,
    "",
  ].join("\n"),
);
